### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by MASSI22** [TCF-BOT-ALGERIE/BOT#3]
not working meme pas matqdrch ta3rf est c q login success or not dima tokhrjlk resarvation closed hata w nediro email khati w mod de pass makach tjrs meme messag

**Comment by aminelfc96** [comment]
so why you are using wrong credentials?
it's not a platform for bugbounty, it's personal use so you have to make sure that the used account is working
and you check if the login is successed if you read the source code of " events.py "

**Comment by MASSI22** [comment]
of course i check my personal account and i easily login in website but
when i put my informations in your bot always showing the same message
(resarvation closed) even when i put a random password always getting the
same means not working corectly

**Comment by aminelfc96** [comment]
Hey,
please do check "http://127.0.0.1:5000/full" on your localhost 
i didn't show errors to not confuse users so they need to make sure they write the right credentials 
you can check if your account is logged in successfully by verify "http://127.0.0.1:5000/full" or "http://127.0.0.1:5000/cookies" or "http://127.0.0.1:5000/TCF (not recommended for verification)" ;
and thanks for the notice i'll fix in the next update
Thank you,

**Comment by MASSI22** [comment]
okay thanks any way for your work i hope you can improve it as well believe
in yourself
god bless bro i'll keep in touch

**Comment by aminelfc96** [comment]
Thank you for the support have a good day

**Comment by MASSI22** [comment]
your welcome good night

**Comment by MASSI22** [comment]
not working
########################################
03/10/2021 09:00:40     Events Fetched
Timeout
03/10/2021 09:01:43     Events Fetched
03/10/2021 09:02:11     Events Fetched
03/10/2021 09:02:23     Events Fetched
03/10/2021 09:02:38     Events Fetched
03/10/2021 09:02:40     Reservation opened
03/10/2021 09:02:40     No Need to update Reservation are open


Le sam. 2 oct. 2021 à 15:18, Massi Amazigh ***@***.***> a
écrit :

> your welcome good night
>

**Comment by MASSI22** [comment]
{
  "__comment__": "AJOUTER TON COMPTE IF-ALGERIE",
  "___comment___": "Vas Voir types.json et antenne.json",
  "email": ***@***.***",
  "password": "azerty90",
  "TCF_TYPE": "1",
  "antenne": "Constantine"
}

Le dim. 3 oct. 2021 à 09:19, Massi Amazigh ***@***.***> a
écrit :

> not working
> ########################################
> 03/10/2021 09:00:40     Events Fetched
> Timeout
> 03/10/2021 09:01:43     Events Fetched
> 03/10/2021 09:02:11     Events Fetched
> 03/10/2021 09:02:23     Events Fetched
> 03/10/2021 09:02:38     Events Fetched
> 03/10/2021 09:02:40     Reservation opened
> 03/10/2021 09:02:40     No Need to update Reservation are open
>
>
> Le sam. 2 oct. 2021 à 15:18, Massi Amazigh ***@***.***> a
> écrit :
>
>> your welcome good night
>>

**Comment by MASSI22** [comment]
please bro do something i tired i have 2 months trying to get rdv

Le dim. 3 oct. 2021 à 09:44, Massi Amazigh ***@***.***> a
écrit :

> {
>   "__comment__": "AJOUTER TON COMPTE IF-ALGERIE",
>   "___comment___": "Vas Voir types.json et antenne.json",
>   "email": ***@***.***",
>   "password": "azerty90",
>   "TCF_TYPE": "1",
>   "antenne": "Constantine"
> }
>
> Le dim. 3 oct. 2021 à 09:19, Massi Amazigh ***@***.***> a
> écrit :
>
>> not working
>> ########################################
>> 03/10/2021 09:00:40     Events Fetched
>> Timeout
>> 03/10/2021 09:01:43     Events Fetched
>> 03/10/2021 09:02:11     Events Fetched
>> 03/10/2021 09:02:23     Events Fetched
>> 03/10/2021 09:02:38     Events Fetched
>> 03/10/2021 09:02:40     Reservation opened
>> 03/10/2021 09:02:40     No Need to update Reservation are open
>>
>>
>> Le sam. 2 oct. 2021 à 15:18, Massi Amazigh ***@***.***> a
>> écrit :
>>
>>> your welcome good night
>>>

**Comment by MASSI22** [comment]
03/10/2021 09:02:39     Attempting reservation for uid 6159681470787
Traceback (most recent call last):
  File "run.py", line 104, in <module>
  File "run.py", line 41, in login
AttributeError: 'NoneType' object has no attribute 'copy'
[504] Failed to execute script run

C:\Users\Dell\Downloads\BOT-main (1)\BOT-main\build-windows-8.1-10-64-bit>{
'{' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Dell\Downloads\BOT-main (1)\BOT-main\build-windows-8.1-10-64-bit>
 "__comment__": "AJOUTER TON COMPTE IF-ALGERIE",
'"__comment__":' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Dell\Downloads\BOT-main (1)\BOT-main\build-windows-8.1-10-64-bit>
 "___comment___": "Vas Voir types.json et antenne.json",
'"___comment___":' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Dell\Downloads\BOT-main (1)\BOT-main\build-windows-8.1-10-64-bit>
 "email": ***@***.***",
'"email":' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Dell\Downloads\BOT-main (1)\BOT-main\build-windows-8.1-10-64-bit>
 "password": "azerty90",
'"password":' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Dell\Downloads\BOT-main (1)\BOT-main\build-windows-8.1-10-64-bit>
 "TCF_TYPE": "1",
'"TCF_TYPE":' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Dell\Downloads\BOT-main (1)\BOT-main\build-windows-8.1-10-64-bit>
 "antenne": "Constantine"
'"antenne":' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Dell\Downloads\BOT-main (1)\BOT-main\build-windows-8.1-10-64-bit>}































































Le dim. 3 oct. 2021 à 09:48, Massi Amazigh ***@***.***> a
écrit :

> please bro do something i tired i have 2 months trying to get rdv
>
> Le dim. 3 oct. 2021 à 09:44, Massi Amazigh ***@***.***> a
> écrit :
>
>> {
>>   "__comment__": "AJOUTER TON COMPTE IF-ALGERIE",
>>   "___comment___": "Vas Voir types.json et antenne.json",
>>   "email": ***@***.***",
>>   "password": "azerty90",
>>   "TCF_TYPE": "1",
>>   "antenne": "Constantine"
>> }
>>
>> Le dim. 3 oct. 2021 à 09:19, Massi Amazigh ***@***.***> a
>> écrit :
>>
>>> not working
>>> ########################################
>>> 03/10/2021 09:00:40     Events Fetched
>>> Timeout
>>> 03/10/2021 09:01:43     Events Fetched
>>> 03/10/2021 09:02:11     Events Fetched
>>> 03/10/2021 09:02:23     Events Fetched
>>> 03/10/2021 09:02:38     Events Fetched
>>> 03/10/2021 09:02:40     Reservation opened
>>> 03/10/2021 09:02:40     No Need to update Reservation are open
>>>
>>>
>>> Le sam. 2 oct. 2021 à 15:18, Massi Amazigh ***@***.***> a
>>> écrit :
>>>
>>>> your welcome good night
>>>>

**Comment by aminelfc96** [comment]
Hey,
i was last couple days,
i'm working on fixing it

**Comment by MASSI22** [comment]
hi welcome back i hope you can fix it as soon as than you bro

**Comment by anisbensmail** [comment]
slm khouya kach jdiid
