### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by Brahimhz** [TCF-BOT-ALGERIE/BOT#5]
quelque questions ou je veux leur reponse svp .

- pour l'antenne dans le fichier config : pour "Alger" par exp.  , je met "Alger" ou  "1".
- dans le fichier sms , la propriete "twilio_account_number" c'est le numero que on doit achete dans la plateforme twillio ???

Merci

**Comment by aminelfc96** [comment]
Salut,
**pour ta première question :**
```
{
  "Alger": "1",
  "Annaba" : "3",
  "Constantine" : "4"
}
```

tu dois écrire la "clé" donc par exemple dans le fichier config.json
tu veux antenne Alger écrire Alger **"respecter le majuscule"** SVP sinon il causera un erreur
et pour le Choix de TCF ils sont classé du 1 à 3 

> j'espère j'ai clarifié avec cette réponse,


**pour la deuxième question:**
tu vas rien acheter, quand tu ouvre un compte twilio tu peux avoir un numéro Trial "Get Trial Number" et le coller dans la valeur du clé **twilio_account_number**

**Comment by Brahimhz** [comment]
@aminelfc96  got my RDV thanks a lot , SMS was on time

**Comment by aminelfc96** [comment]
Very well, good luck.

**Comment by Idir94** [comment]
> Salut, **pour ta première question :**
> 
> ```
> {
>   "Alger": "1",
>   "Annaba" : "3",
>   "Constantine" : "4"
> }
> ```
> 
> tu dois écrire la "clé" donc par exemple dans le fichier config.json tu veux antenne Alger écrire Alger **"respecter le majuscule"** SVP sinon il causera un erreur et pour le Choix de TCF ils sont classé du 1 à 3
> 
> > j'espère j'ai clarifié avec cette réponse,
> 
> **pour la deuxième question:** tu vas rien acheter, quand tu ouvre un compte twilio tu peux avoir un numéro Trial "Get Trial Number" et le coller dans la valeur du clé **twilio_account_number**

Bro can u help to get one , the bot is not working for me!!

**Comment by juba06** [comment]
le bot m'affiche reservation closed mais il y a des RDV.. mais il ne prend pas de RDV c'est normal ?
