### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by choukrus** [TCF-BOT-ALGERIE/BOT#6]
Hello,

to begin with, thanks for the bot,
Only one issue, when it detected an open exam, it just throws an error :  "AttributeError: 'NoneType' object has no attribute 'copy'"

If possible to solve it ? :D 

Thanks.
![image](https://user-images.githubusercontent.com/28727905/135899692-5c4eb891-7ee6-4aa1-8354-815b44d3ff2c.png)

**Comment by ghost** [comment]
I have the same issue. Did you resolve it ?

**Comment by itcef** [comment]
script run.py line 19 :
    return user_cookies.json().get('cookies'), user_header.json().get('headers')

just change to : 
    return user_cookies.json().get('cookies'), user_header.json().get('header')

**Comment by itcef** [comment]
script run.py line 19 : 
`   return user_cookies.json().get('cookies'), user_header.json().get('headers')
`
change to 
`    return user_cookies.json().get('cookies'), user_header.json().get('header')
`

**Comment by MYNAMEISTheGoat** [comment]
> Hello,
> 
> to begin with, thanks for the bot, Only one issue, when it detected an open exam, it just throws an error : "AttributeError: 'NoneType' object has no attribute 'copy'"
> 
> If possible to solve it ? :D
> 
> Thanks. ![image](https://user-images.githubusercontent.com/28727905/135899692-5c4eb891-7ee6-4aa1-8354-815b44d3ff2c.png)

**Comment by MYNAMEISTheGoat** [comment]
Same problem here
